### Login
POST localhost:8080/api/v1/auth/login
Content-Type:  application/json

{
  "email": "admin@mail.ru",
  "password": "123456"
}
### Reg
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Anvar",
  "surname":"AAAAA",
  "email": "adad@mail.ru",
  "phone":"+998996023662",
  "password": "1111"
}