### Create profle
POST localhost:8088/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type:  application/json

{

  "name": "ali",
  "surname": "Aliyev",
  "email": "adminjon@gmail.com",
  "phone": "000",
  "password": "admin",
  "role": "ADMIN",
  "status": "ACTIVED"

}


### Update profle
PUT localhost:8088/api/v1/profile/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type:  application/json

{

  "name": "BBB",
  "surname": "BBB",
  "email": "asl1@gmail.com",
  "phone": "2222",
  "password": "2222",
  "role": "PUBLISHER",
  "status": "ACTIVED"

}

### Update profle
PUT localhost:8088/api/v1/profile/update2/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type:  application/json

{

  "name": "GG",
  "surname": "DD",
  "email": "GGG@gmail.com",
  "phone": "1222",
  "password": "277",
  "role": "PUBLISHER",
  "status": "ACTIVED"

}

### Profile List
GET localhost:8088/api/v1/profile/pagination?page=1&size=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type: application/json


### Profile Delete
DELETE localhost:8088/api/v1/profile/delete/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ

### Profile Filter
DELETE localhost:8088/api/v1/profile/filter
### Create profle
POST localhost:8088/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type:  application/json

{

  "name": "ali",
  "surname": "Aliyev",
  "email": "ravshan@gmail.com",
  "phone": "000",
  "password": "000",
  "role": "PUBLISHER",
  "status": "ACTIVED"

}


### Update profle
PUT localhost:8088/api/v1/profile/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type:  application/json

{

  "name": "BBB",
  "surname": "BBB",
  "email": "asl1@gmail.com",
  "phone": "2222",
  "password": "2222",
  "role": "PUBLISHER"

}

### Update profle
PUT localhost:8088/api/v1/profile/update2/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type:  application/json

{

  "name": "GG",
  "surname": "DD",
  "email": "GGG@gmail.com",
  "phone": "1222",
  "password": "277",
  "role": "PUBLISHER"

}

### Profile List
GET localhost:8088/api/v1/profile/pagination?page=1&size=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ
Content-Type: application/json


### Profile Delete
DELETE localhost:8088/api/v1/profile/delete/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMjU4MjMsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMxMTIyMjMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.TAa46ERpDreWyNk5njbZpNxS_Qrkp_0SNaB5CvPdGnmtLQWy7ZtQM0NhG8HuMAD92MkP1HgaE_erSAPxKbplJQ


### Profile Filter
DELETE localhost:8088/api/v1/profile/filter
